### ISSUE TITLE
Asynchronous Federated Learning diagrams needs improvement. 

### ISSUE THREAD

**Issue by Sukanya-rs** [OpenMined/design#10]
## Description
Please help me in improvising the diagrams of the blog: [Asynchronous Federated Learning](https://medium.com/@sukanya.me/asynchronous-federated-learning-3c52c5b1a409), so that it can be published as per  OpenMined standards. 

## Are you interested in working on this improvement yourself?
- Definitely,  I can try but would need help as I am not sure what tools are expected to be used to match OpenMined branding guide. 

## Additional Context
<img width="1436" alt="Screenshot 2022-07-11 at 10 37 41 PM" src="https://user-images.githubusercontent.com/78011093/178319478-c3b80d34-4b44-4bcd-8207-65555e69ee0d.png">
<img width="1169" alt="Screenshot 2022-07-11 at 10 38 03 PM" src="https://user-images.githubusercontent.com/78011093/178319549-d2d93816-8239-4507-93b1-effe7a2db654.png">

**Comment by Poppy22** [comment]
Hello! I'm currently collaborating with @Sukanya-rs on this issue ^^

**Comment by Kiaka007** [comment]
This was completed by Carmen
