### ISSUE TITLE
Design for blog part 2 Our privacy opportunity

### ISSUE THREAD

**Issue by AbinavRavi** [OpenMined/design#5]
## What is this asset supporting?
recreate graphics according to the design guideline for a new post on our privacy opportunity series

## Who are we creating this for?
Writing team @AbinavRavi 

## Content
[](url)
## Size & Format
No specification high-quality JPEG for the blog is sufficient

**Comment by Kiaka007** [comment]
Hey @AbinavRavi could you link to the blog post issue this graphic is connected to?

**Comment by Kiaka007** [comment]
@AbinavRavi Asset is ready to go:
https://github.com/OpenMined/design/blob/assets/diagrams/structured-transparency.jpg
