### ISSUE TITLE
To create a better representation of domain & networks need for a blog.

### ISSUE THREAD

**Issue by Sukanya-rs** [OpenMined/design#6]
## What is this asset supporting?
To create a better representation of domain & networks need for a blog "[Deploying domain node](https://github.com/orgs/OpenMined/projects/31#card-74339377)". 

## Why?
I have created a Diagram but it needs better presentation which I believe can be done by the design team. Also, Data centric FL flow of information needs to be updated.

## Who are we creating this for?
For OpenMined

## Content
The link to the blog which is yet to be reviewed but need diagram update. [https://docs.google.com/document/d/112pJ3yRKnfEv57UtAMqddOFHVEt7fvEgf9zNRT0UpME/edit?usp=sharing]

## Size & Format
It's a Google doc file. Will share the ppt on slack when contacted by relevant design team member. 

## Ideas
In the link, Please refer to "Visualising Data-centric FL with an example". Also, Data-centric FL Diagrams that shows the flow of requests & information. 

Thank you !!

**Comment by Sukanya-rs** [comment]
**Request**: As a part of writing a blog :[Deploying a Single Domain Node](https://docs.google.com/document/d/112pJ3yRKnfEv57UtAMqddOFHVEt7fvEgf9zNRT0UpME/edit), I had requested design team to help with out the Fig2,3 and 4 diagrams to be modified and better represented, which is currently reviewed by Mark(@m15e). 

> 1. Fig2 & 3 does not mention anywhere the usage of PyGrid or HAGrid and thought of adding it in the diagram. 
> ![Fig2 : Model-Centric AI](https://user-images.githubusercontent.com/78011093/161381246-aeea0627-6021-4323-933a-b22c267b9464.jpeg)
> 
> ![Fig3 : Data-Centric AI](https://user-images.githubusercontent.com/78011093/161381247-1df6f717-d52b-4127-83f4-ad402d782175.jpeg)
> 
> 2. Requested for better representation of “Domains inside networks” based on the digram that I had created as an example. 
> ![Fig 4 : Visualising Data-Centric AI using an Example](https://user-images.githubusercontent.com/78011093/161381249-707a6c4f-c5ad-4d88-807c-295e8a01ebf4.jpeg)
> 

Conclusion:
1. Fig2, 3 are not be included in the blog as they are based on old models as per discussion with @madhavajay. 
2. Fig 4 represents “Many domains inside the Networks” which currently a feature still being built and part of syft 0.7.0 and also domains needs to have a handshake with networks using “Network agreement” which is not part of the [Lecture 2 : Introduction to Remote Data Science](https://courses.openmined.org/courses/introduction-to-remote-data-science) and hence including it in the blog may lead to confusions for the readers and hence dropping it to be added in the blog as of now and closing the issue.

Thank you Kyoko(@Kiaka007), Berke Atropat from Design team in co-ordinations, @IonesioJunior for reviewing the Fig4 initially,  @Madhavajay for pitching in quickly and giving me the feedback ! :)

**Comment by Kiaka007** [comment]
@Sukanya-rs please see if these will fit for what you need in the blog post.

**Note:** 
- The diagram "domain-node-cloud-instances" should be fine to run with.
- The diagram "network-node-simplified" can be run with if needed but if the post can be communicated without then please exclude.

**Assets**
https://github.com/OpenMined/design/pull/7/files
